name: repro
on:
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Collect Workflow Telemetry
        uses: tspascoal/workflow-telemetry-action@master

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Tests Results
          files: '**/surefire-reports/TEST-*.xml'
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
